### ISSUE TITLE
US1: show list of all movies / series 

### ISSUE THREAD

**Issue by jonashinzmann** [jonashinzmann/MovieHUB#2]
## Value Proposition

As a user, I want a list that displays all movies and series along with their streaming service availability
in order to to view the relevant information.

​

## Description
<img width="323" alt="Bildschirmfoto 2023-07-19 um 11 28 02" src="https://github.com/jonashinzmann/MovieHUB/assets/134228708/3ec80cd0-0a57-4405-994e-b297d4c9d729">

​

## Acceptance Criteria

- [ ] The header is fixed at the top
- [ ] The list shows the name of the movie or series
- [ ] The list includes the streaming service for each movie or series 
      ​

## Tasks

- [ ] Create a new feature branch named "MovieList"
- [ ] Create a Movie-Component that displays name and streaming-provider
- [ ] Use SWR-hook to fetch the data from the external API
- [ ] Implement the logic to map over the data obtained from the API and render each movie and series as a list item in the "MovieList" component
- [ ] Display the name of the movie or series and the associated streaming service
- [ ] Apply CSS styles to the "MovieList" component to make the list visually appealing and easy to read

**Comment by Roland-Hufnagel** [comment]
Hey Jonas. Great Job! Your first userstory looks very good to me. I think it is a big one but that's okay. I just have some minor important suggestions:
- Since a title is shown in the wireframe you should mention it in the acceptance-criteria (more or less detailed, e.g. 'the header is fixed at the top') and in the tasks
- I would suggest to create and use a 'Movie-Component' that renders each fetched movie inbetween the 'MovieList-Component'. The task could be: 'Create a Movie-Component that displays name and streaming-provider'
- 'Use SWR-hook to fetch the data from the external API' is detailed enough

please include my suggestions in your story in push it once more in the channel.

**Comment by actyvystom** [comment]
LGTM 🚀
