### ISSUE TITLE
US2: add a Search-Field

### ISSUE THREAD

**Issue by jonashinzmann** [jonashinzmann/MovieHUB#3]
## Value Proposition

As a user
I want an Search-Field with a placeholder and a Submit-Button
in order to search for certain movies or series.

 
​

## Description
<img width="323" alt="Wireframe_US2" src="https://github.com/jonashinzmann/MovieHUB/assets/134228708/1874c6ce-f96f-4bc3-9ca6-fdb28441b7cb">

​

## Acceptance Criteria

- [ ] The Search-Field should have a placeholder
- [ ] The Search-Field should have a Submit-Button
      ​

## Tasks

- [ ] Create a new feature branch named "US2-Search-Field"
- [ ] Create a new component named "SearchField" that will be responsible for rendering the search Search-Field and the Submit-Button
- [ ] Implement the Search-Field using the useState hook to manage user input.
- [ ]  Implement a Submit-Button in the "SearchField" component
- [ ]  Create a function to handle the submit action when the user clicks the Submit-Button
- [ ] Apply CSS styles to the "InputField" component to make it visually appealing and consistent with the rest of the application.
