### ISSUE TITLE
US3: add a Details-Page

### ISSUE THREAD

**Issue by jonashinzmann** [jonashinzmann/MovieHUB#4]
## Value Proposition

As a user
I want to to have a Details-Page  
in order to get details from certain movies or series  
​

## Description
 <img width="301" alt="Wireframe_US3" src="https://github.com/jonashinzmann/MovieHUB/assets/134228708/009cb1d2-c94e-4acf-84cd-e8698be1f76f">

​

## Acceptance Criteria

- [ ] The Details-Page should display relevant details about the selected movie or series (e.g. genre, year, cast, description and a picture)
- [ ] When the title on the homepage is clicked, it will navigate you to the Details-Page. 
- [ ] The Details-Page should have a Back-Button
      ​

## Tasks

- [ ] Create a new feature branch named "US3-Details-Page"
- [ ] Create a component named "Details-Page"
- [ ] Map over the necessary data and render each movie and series as a list item in the "Details-Page" component
- [ ] Create a Back-Button, that takes the user back to the homepage
- [ ] Apply CSS styles to the "Details-Page" component to make the list visually appealing and easy to read

**Comment by AliaksandraNovikava** [comment]
Hey @jonashinzmann.

Your US is very small and simple👍

But there are some things I would like to address:

1. It would be more logical to swap the first two acceptance criteria: first you click on a title and then you go to the details page.
2. How about adding one more acceptance criteria:
- [ ] Clicking the back-button shows the homepage
3. How about naming your component `MovieDetails`, because it'a a component and not a page.
4. You don't need to use the map method, because you don't really want to see a list in your details page but a detailed information of a certain movie. Instead:
- [ ] Create the page pages/movies/[slug] that renders `MovieDetails`

**Comment by FlorianNova** [comment]
Looks good to me! :)
