### ISSUE TITLE
US4: add a Favourites-Page

### ISSUE THREAD

**Issue by jonashinzmann** [jonashinzmann/MovieHUB#5]
## Value Proposition

As a user   
I want to have a Favourites-Page  
in order to save movies and series
​

## Description
<img width="325" alt="Wireframe_US4" src="https://github.com/jonashinzmann/MovieHUB/assets/134228708/3833eee6-5d54-47e4-895e-392c621e8507">

​

## Acceptance Criteria

- [ ] on the page you should be able to create lists to structure the films and series that you want to save 
- [ ] there should be a "create list"-button    ​

## Tasks

- [ ] Create a new feature branch named "US4-Favourites-Page"
- [ ] Create a new Component named "Favourites"
- [ ] Add a "Create List" button to the favorites page

**Comment by mrrubinello** [comment]
einfach gehalten / easy and overviewable , so and okay from my side
I think in future Us you will explain how you can add movies to those lists
