### ISSUE TITLE
US5: add a navigation

### ISSUE THREAD

**Issue by jonashinzmann** [jonashinzmann/MovieHUB#6]
## Value Proposition

As a user  
I want a navigation bar
in order to quickly and easily access various areas of the app
​

## Description
![Wireframe_US5](https://github.com/jonashinzmann/MovieHUB/assets/134228708/98c6c603-5618-41d4-bed5-b6aea6168f9b)

​

## Acceptance Criteria

- [ ] The navigation bar should be on every page of the app
- [ ] The links to the other pages should be icons
- [ ] The links should change there color if you hover over them

 ​
## Tasks

- [ ] Create a new feature branch named "US5-navigation-bar"
- [ ] Create a component named "NavigationBar"
- [ ] Implement Next.js routing to enable navigation between pages when users click on the navigation links
- [ ] Set up the basic HTML structure within the navigation bar component

**Comment by mrrubinello** [comment]
hi jonas,

looks good, I understand what you want to built :-)

question: if you want to create icons for the links, why don't you use them already in the wireframe?
q2: "When you are on a page, the associated link should have changed color", can you explain which link?

tasks make sense to me (y)

**Comment by CorneliusMoe** [comment]
LGTM :)
